mikepenz/release-changelog-builder-action

.github/workflows/test.yml
- add automated build to create release notes
=> [CI] Introduce automated release build

README.md
- add contribution notes 
- define as fix to showcase
=> Add contribution notes

.github/workflows/ci.yml, README.md
=> dev -> main

.github/workflows/ci.yml
=> Specify toTag for the automated release generation

__tests__/main.test.ts, configs/configuration.json, src/releaseNotes.ts
- introduce better handling of cases in which invalid references are provided, return an empty changelog and send out error
=> Improved handling for non existing tags

src/configuration.ts
- adjust defaults to already provide a great base set of categories
- define categories
```json
categories: [
{
title: '## 🚀 Features',
labels: ['feature']
},
{
title: '## 🐛 Fixes',
labels: ['fix']
},
{
title: '## 🧪 Tests',
labels: ['test']
}
]
```
=> Improved defaults if no configuration is provided

.github/workflows/ci.yml, README.md, configs/configuration_repo.json
- introduce `other` category for library changelog
=> Improve changelog generation of project

.github/workflows/ci.yml
- add back checkout to have configuration available
=> Adjust release github action

.github/workflows/ci.yml
- introduce new step, showcasing generation of changelog for an external configuration
=> Showcase external repo changelog generation

.github/workflows/ci.yml, README.md, src/main.ts, src/releaseNotes.ts
- introduce more output values, and a more detailed description
=> Introduce additional output values

README.md, __tests__/main.test.ts, action.yml, src/main.ts, src/releaseNotes.ts, src/utils.ts
- add better table to describe input configuration options
- introduce new capability to enforce a build failure 
- introduce config to fail on error instead of just logging
- simplify main logic, move functionality in other classes
- add new configuration ptions
=> Introduce configuration to fail on errors

README.md, package.json
- add more keywords and update description
=> Update package.json to updated description

action.yml
- add updated description to action.yml
=> Updated action.yml description

README.md, __tests__/tags.test.ts, src/configuration.ts, src/releaseNotesBuilder.ts, src/tags.ts
- provide alternative method to sort tags 
- introduce option configuration allowing to specify which method to pick
- semver (default)
- alphabetical sort order (sort)
- add information about approach to resolving tag before
=> Introduce alternative tag sorting algorithm

action.yml
- update documentation about outputs from the action
=> Enhance actions.yml

configs/configuration_repo.json
- include dependency updates in changelog
=> Include dependency updates in changelog

README.md
Just so if someone else is like me and tries to directly copy and paste the example it will work.
=> Add missing `jobs` key in full sample

README.md, package-lock.json
- update documentation with flags config for label_extractor
=> Update documentation 

src/utils.ts
- introduce additional logging to better identify if configuration was configured and properly loaded.
- print configuration as json in debug
- Helpful in situations as outlined in: https://github.com/mikepenz/release-changelog-builder-action/issues/483
=> Expand logging in regards to configuration loading

.github/workflows/ci.yml
- use the proper configuration path
=> Fix release action config path

package-lock.json, package.json
```
"webpack": "^5.68.0"
"@typescript-eslint/parser": "^5.10.2",
"@types/node": "^17.0.14",
"eslint": "^8.8.0",
```
=> NPM Dependency updates 

README.md
- Update  README to use different release action
- FIX https://github.com/mikepenz/release-changelog-builder-action/issues/790
=> Update README to use different release action

.github/workflows/check-dist.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
- upgrade CI pipelines 
- introduce dist check
=> Improve CI pipelines

package-lock.json, package.json
- update dependencies
```
"webpack": "^5.74.0"
```
```
"@types/node": "^18.6.1",
"@typescript-eslint/parser": "^5.31.0",
"eslint-plugin-github": "^4.3.7",
```
=> Update dependencies | Webpack 5.74.0

README.md
- add note on local testing / debugging via Visual Code
=> Include `Local Testing` section in README

README.md
Small adjustment, only noticed because I'm setting up a custom test for local dev. Cheers!
=> Fix custom test case TS file by supplying the correct number of arguments to ReleaseNotesBuilder

.devcontainer/devcontainer.json
- introduce a `.devcontainer.json` config with node 16
=> DevContainer support

src/transform.ts
Avoid "undefined" if title is not specified in category configuration.
=> Add category title to changelog only if present

package-lock.json, package.json, pr-collector/package-lock.json, pr-collector/package.json
```
@types/node                ^20.2.5  →  ^20.3.0
@typescript-eslint/parser  ^5.59.8  →  ^5.59.9
```
=> Dev dependency upgrades

.devcontainer/devcontainer.json, .devcontainer/postCreateCommand.sh
- improve the devcontainer by also building the `pr-collector` within
=> Improve `devcontainer` setup

README.md
The current example was failing here:
```
TypeError: Cannot read properties of undefined (reading 'filter')
235 |  */
236 | export function filterTags(tags: TagInfo[], tagResolver: TagResolver): TagInfo[] {
> 237 |   const filter = tagResolver.filter
|                              ^
238 |   if (filter !== undefined) {
239 |     const regex = new RegExp(filter.pattern.replace('\\\\', '\\'), filter.flags ?? 'gu')
240 |     const filteredTags = tags.filter(tag => tag.name.match(regex) !== null)
at filterTags (src/tags.ts:237:30)
at Tags.<anonymous> (src/tags.ts:143:26)
at fulfilled (src/tags.ts:28:58)
```
That didn't make sense and it took me a while to find out that `mergeConfiguration` was required in order to apply the default configuration.
This PR fixes the issue, but probably we can …
=> Update custom.test.ts in README.md

.github/workflows/ci.yml
- update the version of used actions
=> Update CI action versions

__tests__/releaseNotesBuilder.test.ts, __tests__/releaseNotesBuilderPull.test.ts, caches/rcba_0.0.1-0.0.3_cache.json, caches/rcba_0.0.1-0.0.3_commit_cache.json, caches/rcba_0.0.2-0.0.3_cache.json, caches/rcba_0.3.0-0.5.0_cache.json, caches/rcba_0.9.1-0.9.5_cache.json, caches/rcba_1.3.1-1.4.0_base_develop_cache.json, caches/rcba_1.3.1-1.4.0_base_main_cache.json, caches/rcba_5ec7a2-fa3788_cache.json, caches/stackzy_bd3242-17a9e4_cache.json
- Update various test-cases to operate based on cached data retrieved from the API
- especially for historical data where PRs from over 2+ years is pulled that makes a major difference
=> Test optimisations

.github/dependabot.yml
- group together dev dependencies
=> Dependabot group

README.md
- add documentation for `permission` token scope
=> Update GA permission scopes

README.md, package-lock.json, package.json
- update readme and include gitea information
- fix note, warning, important highlights
- update version to 4.1.0
=> Improve README to include Gitea, and fix highlights

.github/workflows/ci.yml
- generate full changelog for releases
=> [CI] Optimize release changelog config

README.md
- rework README and add new example for commit mode
=> Rework README structure

.github/workflows/ci.yml
=> Adjust CI condition

configs/configuration_repo.json
=> Improve release notes template

.github/workflows/check-dist.yml, .github/workflows/codeql-analysis.yml
=> Update Actions versions

.github/dependabot.yml
- enable dependabot updates for GitHub Actions
=> [CI] Enable Dependabot for GitHub Actions

README.md
- fix README for gitea
- FIX https://github.com/mikepenz/release-changelog-builder-action/issues/1452#issuecomment-2856588150
=> Fix documentation for gitea

package.json
- combined run for tests to get a full report
=> Improve CI test run report

.github/workflows/check-dist.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml
chore: update GitHub Actions to use checkout@v5
=> Update to checkout@v5
